version: "3.9"

services:
  app:
    build:
      context: .
      args:
      - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=secret
      - DEBUG=1
    depends_on:
      - db
    tty: true
    command: tail -f /dev/null
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=devuser
      - POSTGRES_DB=devdb


volumes:
  db-dev-data:
  dev-static-data:
